name: Auto Package

on:
  push:
    branches:
    - main
    paths:
    - ATM7-To_The_Sky
  workflow_dispatch: {}

jobs:
  Packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      
      - name: Fix FTBQuest path
        run: |
          cd ATM7-To_The_Sky/config
          mv ftbquests quests
          mkdir ftbquests
          mv quests ftbquests

      - name: Remove backup folder
        run: |
          cd ATM7-To_The_Sky
          rm -r backup

      - name: Move License
        run: |
          cp LICENSE ATM7-To_The_Sky/kubejs/assets/kubejs/lang/

      - name: Make ATM7 - To The Sky Archive
        run: |
          cd ATM7-To_The_Sky
          zip -r ../TranslateModPack-ATM7sky.zip *

      - name: Make Checksum
        id: checksum
        run: |
          echo "::set-output name=sum-01::$(sha256sum TranslateModPack-ATM7sky.zip)"

      - name: Make Git Version
        id: version
        run: |
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: Make Current Time
        id: current_time
        run: |
          echo "::set-output name=time::$(TZ='Asia/Taipei' date +'最後更新：%Y 年 %m 月 %d 日 %H 點 %M 分')"

      - name: Push Pack to Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: 模組任務翻譯包 (git ${{ steps.version.outputs.sha_short }})
          body: |
            ## 📝 下載
            下載下方的 Assets 內的對應模組任務翻譯包
            並將其解壓縮**覆蓋**至你的 `minecraft/` 目錄中
            (該目錄必須有同時顯示 config resourcepack 資料夾等等，才會是正確的位置)

            ## ⭐ 更新
            將新版本的模組翻譯包一樣在 `minecraft/` 資料夾中再度解壓縮並覆蓋即可！

            > ${{ steps.current_time.outputs.time }}

            ## ✅ Checksum
            ```
            ${{ steps.checksum.outputs.sum-01 }}
            ```
